export const initialTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  paragraph: 'nl-paragraph',
  quote: 'nl-quote',
  heading: {
    h1: 'nl-heading-h1',
    h2: 'nl-heading-h2',
    h3: 'nl-heading-h3',
    h4: 'nl-heading-h4',
    h5: 'nl-heading-h5',
    h6: 'nl-heading-h6',
  },
  list: {
    nested: {
      listitem: 'nl-nested-listitem',
    },
    ol: 'nl-list-ol',
    ul: 'nl-list-ul',
    listitem: 'nl-listItem',
    listitemChecked: 'nl-listItemChecked',
    listitemUnchecked: 'nl-listItemUnchecked',
  },
  hashtag: 'nl-hashtag',
  image: 'nl-image',
  link: 'nl-link',
  text: {
    bold: 'nl-textBold',
    code: 'nl-textCode',
    italic: 'nl-textItalic',
    strikethrough: 'nl-textStrikethrough',
    subscript: 'nl-textSubscript',
    superscript: 'nl-textSuperscript',
    underline: 'nl-textUnderline',
    underlineStrikethrough: 'nl-textUnderlineStrikethrough',
  },
  code: 'nl-code',
  codeHighlight: {
    atrule: 'nl-tokenAttr',
    attr: 'nl-tokenAttr',
    boolean: 'nl-tokenProperty',
    builtin: 'nl-tokenSelector',
    cdata: 'nl-tokenComment',
    char: 'nl-tokenSelector',
    class: 'nl-tokenFunction',
    'class-name': 'nl-tokenFunction',
    comment: 'nl-tokenComment',
    constant: 'nl-tokenProperty',
    deleted: 'nl-tokenProperty',
    doctype: 'nl-tokenComment',
    entity: 'nl-tokenOperator',
    function: 'nl-tokenFunction',
    important: 'nl-tokenVariable',
    inserted: 'nl-tokenSelector',
    keyword: 'nl-tokenAttr',
    namespace: 'nl-tokenVariable',
    number: 'nl-tokenProperty',
    operator: 'nl-tokenOperator',
    prolog: 'nl-tokenComment',
    property: 'nl-tokenProperty',
    punctuation: 'nl-tokenPunctuation',
    regex: 'nl-tokenVariable',
    selector: 'nl-tokenSelector',
    string: 'nl-tokenSelector',
    symbol: 'nl-tokenProperty',
    tag: 'nl-tokenProperty',
    url: 'nl-tokenOperator',
    variable: 'nl-tokenVariable',
  },
};