export const initialTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  paragraph: 'nbe-paragraph',
  quote: 'nbe-quote',
  heading: {
    h1: 'nbe-heading-h1',
    h2: 'nbe-heading-h2',
    h3: 'nbe-heading-h3',
    h4: 'nbe-heading-h4',
    h5: 'nbe-heading-h5',
    h6: 'nbe-heading-h6',
  },
  list: {
    nested: {
      listitem: 'nbe-nested-listitem',
    },
    ol: 'nbe-list-ol',
    ul: 'nbe-list-ul',
    listitem: 'nbe-listItem',
    listitemChecked: 'nbe-listItemChecked',
    listitemUnchecked: 'nbe-listItemUnchecked',
  },
  hashtag: 'nbe-hashtag',
  image: 'nbe-image',
  link: 'nbe-link',
  text: {
    bold: 'nbe-textBold',
    code: 'nbe-textCode',
    italic: 'nbe-textItalic',
    strikethrough: 'nbe-textStrikethrough',
    subscript: 'nbe-textSubscript',
    superscript: 'nbe-textSuperscript',
    underline: 'nbe-textUnderline',
    underlineStrikethrough: 'nbe-textUnderlineStrikethrough',
  },
  code: 'nbe-code',
  codeHighlight: {
    atrule: 'nbe-tokenAttr',
    attr: 'nbe-tokenAttr',
    boolean: 'nbe-tokenProperty',
    builtin: 'nbe-tokenSelector',
    cdata: 'nbe-tokenComment',
    char: 'nbe-tokenSelector',
    class: 'nbe-tokenFunction',
    'class-name': 'nbe-tokenFunction',
    comment: 'nbe-tokenComment',
    constant: 'nbe-tokenProperty',
    deleted: 'nbe-tokenProperty',
    doctype: 'nbe-tokenComment',
    entity: 'nbe-tokenOperator',
    function: 'nbe-tokenFunction',
    important: 'nbe-tokenVariable',
    inserted: 'nbe-tokenSelector',
    keyword: 'nbe-tokenAttr',
    namespace: 'nbe-tokenVariable',
    number: 'nbe-tokenProperty',
    operator: 'nbe-tokenOperator',
    prolog: 'nbe-tokenComment',
    property: 'nbe-tokenProperty',
    punctuation: 'nbe-tokenPunctuation',
    regex: 'nbe-tokenVariable',
    selector: 'nbe-tokenSelector',
    string: 'nbe-tokenSelector',
    symbol: 'nbe-tokenProperty',
    tag: 'nbe-tokenProperty',
    url: 'nbe-tokenOperator',
    variable: 'nbe-tokenVariable',
  },
};